spring:
  application:
    name: boot-session-ignite
  thymeleaf:
    cache: false
  security:
    user:
      password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
server:
  port: 8080